### ISSUE TITLE
logout field 

### ISSUE THREAD

**Issue by daliMejri** [symbiose/symbiose#520] opened 2015-09-07 12:11 UTC
I have problem with logout user on local server .
Maximum execution time of 30 seconds exceeded in C:\Program Files\EasyPHP-DevServer-14.1VC9\data\localweb\projects\symbiose-master\lib\dao\localfs\LocalFs.class.php on line 227
at api calling action "disconnect" in module "user" with arguments {}

can you give me the procedure used to logout.

**Comment by emersion** [comment] 2015-09-18 15:05
Duplicate of #436

**Closed by emersion** 2015-09-18 15:05 UTC
Labels: duplicate
